apiVersion: apps/v1
kind: Deployment
metadata:
  name: diagnostics-qa
spec:
  replicas: 1
  selector:
    matchLabels:
      role: diagnostics-qa
  minReadySeconds: 20
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        role: diagnostics-qa
    spec:
      containers:
        - name: diagnostics-qa
          image: us.gcr.io/basearchitecture/diagnostics-qa
          ports:
            - containerPort: 80
