apiVersion: v1
kind: Service
metadata:
  name: diagnostics-lb
  namespace: qa
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  selector:
    role: diagnostics
  type: LoadBalancer
  loadBalancerIP: "34.135.17.40"


    