apiVersion: v1
kind: Service
metadata:
  name: xxx
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  selector:
    role: xxx
  type: LoadBalancer
  loadBalancerIP: xxx


    